App\Entity\Direccion:
  attributes:
    id:
      groups: ['post_direccion', 'get_direccion_cliente']

    calle:
      groups: ['post_direccion', 'get_direccion_cliente']

    numero:
      groups: ['post_direccion', 'get_direccion_cliente']

    puerta_piso_escalera:
      groups: ['post_direccion', 'get_direccion_cliente']

    cod_postal:
      groups: ['post_direccion', 'get_direccion_cliente']

    cliente:
      groups: ['post_direccion']

    municipio:
      groups: ['post_direccion', 'get_direccion_cliente']

    provincia:
      groups: ['post_direccion', 'get_direccion_cliente']