App\Entity\Municipios:
  attributes:
    id:
      groups: ['post_direccion', 'get_direccion_cliente', 'municipios']

    municipio:
      groups: ['post_direccion', 'get_direccion_cliente', 'municipios']