App\Entity\Provincias:
  attributes:
    id:
      groups: ['post_direccion', 'get_direccion_cliente', 'provincias']

    provincia:
      groups: ['post_direccion', 'get_direccion_cliente', 'provincias']